# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Sverchok Dockerised CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Make Release Zip
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: 'sverchok.zip'
          exclusions: '*.git* /.github/* /docs/*'

      - name: Step with docker to echo a string
        uses: 'kevinwright/sverchok-test-action@v0.0.1'
        args: >-
          -workdir /addon-test
          Hello Docker !    