# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Sverchok Dockerised CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2
      -
        run: |
          mkdir -p /tmp/zipbuild/sverchok
          rsync -av . /tmp/zipbuild/sverchok --exclude '.git**' --exclude 'docs' 
      -
        name: Make Release Zip
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          path: '/tmp/zipbuild'
          filename: 'sverchok.zip'
          exclusions: '*.git* /.github/* /docs/*'
      -
        name: Test in Docker
        uses: docker://ghcr.io/kevinwright/sverchok-testing-image:latest
      -
        name: Upload zip
        uses: actions/upload-artifact@v2
        with:
          name: sverchok.zip
          retention-days: 5
          path: |
            ./sverchok.zip

